  - name: variables from inventoryfile
    hosts: local
    connection: local
    tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "course is {{COURSE}},Duration is {{DURATION}},Trainer is {{TRAINER}}"
        #here variables are not there inplay level/task level/ file/prompt